### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by furnaceX** [Shopify/shopify-demo-app-node-react#146]
# Issue summary

When I issue the build command "npm run build", I get an error.

## Expected behavior

I expect it to build

## Actual behavior

I get the following output: 
<details>
Compiled successfully.

> Build error occurred
Invariant Violation:
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/node-fetch.

For example:
import fetch from 'node-fetch';
import { createHttpLink } from 'apollo-link-http';

const link = createHttpLink({ uri: '/graphql', fetch: fetch });
    at new InvariantError (/sample-embedded-app/node_modules/ts-invariant/lib/invariant.js:16:28)
    at Object.exports.checkFetcher (/sample-embedded-app/node_modules/apollo-link-http-common/lib/index.js:65:15)
    at Object.exports.createHttpLink (/sample-embedded-app/node_modules/apollo-link-http/lib/httpLink.js:9:31)
    at new HttpLink (/sample-embedded-app/node_modules/apollo-link-http/lib/httpLink.js:140:42)
    at new DefaultClient (/sample-embedded-app/node_modules/apollo-boost/lib/bundle.cjs.js:133:20)
    at Module.1TCz (/sample-embedded-app/.next/server/static/NGLlw2QWWO3CnSppY1oud/pages/_app.js:147:16)
    at __webpack_require__ (/sample-embedded-app/.next/server/static/NGLlw2QWWO3CnSppY1oud/pages/_app.js:23:31)
    at Object.0 (/sample-embedded-app/.next/server/static/NGLlw2QWWO3CnSppY1oud/pages/_app.js:106:18)
    at __webpack_require__ (/sample-embedded-app/.next/server/static/NGLlw2QWWO3CnSppY1oud/pages/_app.js:23:31)
    at /sample-embedded-app/.next/server/static/NGLlw2QWWO3CnSppY1oud/pages/_app.js:91:18 {
  framesToPop: 1,
  name: 'Invariant Violation'
}
Automatically optimizing pages .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample-embedded-app@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample-embedded-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-06T02_31_34_456Z-debug.log

</details>
## Steps to reproduce the problem

1. Install the shopify-demo-app-node-react
2. npm run build

**Comment by ahkjxy** [comment]
yea, i have too

**Comment by kisuka** [comment]
Wrote a fix here: https://github.com/Shopify/shopify-demo-app-node-react/pull/157
